urls:
  vit_l: "https://dl.fbaipublicfiles.com/segment_anything/sam_vit_l_0b3195.pth"
  vit_h: "https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth"
  vit_b: "https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth"